removing dry-running of tarballs

diff --git a/.github/workflows/build/action.yaml b/.github/workflows/build/action.yaml
--- a/.github/workflows/build/action.yaml
+++ b/.github/workflows/build/action.yaml
@@ -55,25 +55,26 @@ runs:
         branch: ${{ github.head_ref }}
         ssh: true
 
-    - name: Dry run tarballs
-      shell: bash
-      run: |
-        #!/bin/bash
+    # TODO: see if this is even possible
+    # - name: Dry run tarballs
+    #   shell: bash
+    #   run: |
+    #     #!/bin/bash
 
-        set -euo pipefail
-        bazel query ... | grep -E "tarball$" | while IFS= read -r target; do
-            echo "Testing $target"
-            bazel run $target
+    #     set -euo pipefail
+    #     bazel query ... | grep -E "tarball$" | while IFS= read -r target; do
+    #         echo "Testing $target"
+    #         bazel run $target
 
-            image=$(echo $target | awk -F: '{ print $1 }' | awk -F/ '{ print $NF }')
-            image="localhost/$image"
-            echo "Testing dry run on image: $image"
-            ret=0
-            output=$(docker run --rm $image --help 2>&1) || ret=$?
-            if [ "$ret" != "0" ]
-            then
-              echo "$image failed to run.  Output:" >&2
-              echo "$output" >&2
-              exit "$ret"
-            fi
-        done
+    #         image=$(echo $target | awk -F: '{ print $1 }' | awk -F/ '{ print $NF }')
+    #         image="localhost/$image"
+    #         echo "Testing dry run on image: $image"
+    #         ret=0
+    #         output=$(docker run --rm $image --help 2>&1) || ret=$?
+    #         if [ "$ret" != "0" ]
+    #         then
+    #           echo "$image failed to run.  Output:" >&2
+    #           echo "$output" >&2
+    #           exit "$ret"
+    #         fi
+    #     done
