reverted 2 commits

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -14,60 +14,58 @@ jobs:
   bazel:
     runs-on: ubuntu-20.04
     steps:
-      - name: Debug print github context
-        run: echo '${{ toJSON(github) }}'
-      # - uses: actions/checkout@v4
-      # - name: Setup runner
-      #   uses: ./.github/workflows/manage-runner-pre
+      - uses: actions/checkout@v4
+      - name: Setup runner
+        uses: ./.github/workflows/manage-runner-pre
 
-      # ########################################
-      # # Build and test
-      # ########################################
-      # - run: bazel build ...
-      #   name: Building
-      # - run: bazel test ...
-      #   name: Testing
+      ########################################
+      # Build and test
+      ########################################
+      - run: bazel build ...
+        name: Building
+      - run: bazel test ...
+        name: Testing
 
-      # ########################################
-      # # Prepare release
-      # ########################################
-      # - name: Upload artifact for release
-      #   uses: actions/upload-artifact@v2
-      #   if: startsWith(github.ref, 'refs/tags/v')
-      #   with:
-      #     name: dre
-      #     path: bazel-out/k8-opt/bin/rs/cli/dre
-      # - name: Call prepare release
-      #   if: startsWith(github.ref, 'refs/tags/v')
-      #   uses: ./.github/workflows/prepare-release.yml
-      #   with:
-      #     ARTIFACT_NAME: dre
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      ########################################
+      # Prepare release
+      ########################################
+      - name: Upload artifact for release
+        uses: actions/upload-artifact@v2
+        if: startsWith(github.ref, 'refs/tags/v')
+        with:
+          name: dre
+          path: bazel-out/k8-opt/bin/rs/cli/dre
+      - name: Call prepare release
+        if: startsWith(github.ref, 'refs/tags/v')
+        uses: ./.github/workflows/prepare-release.yml
+        with:
+          ARTIFACT_NAME: dre
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # ########################################
-      # # Upload container images
-      # ########################################
-      # - name: Login to GitHub Container Registry
-      #   uses: docker/login-action@v3
-      #   with:
-      #     registry: ghcr.io
-      #     username: ${{ github.actor }}
-      #     password: ${{ secrets.GITHUB_TOKEN }}
-      # - name: Push images to GitHub Container Registry
-      #   if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
-      #   run: bazel query --noshow_progress 'kind("oci_push", ...)' | xargs -I_target bazel run _target -- --tag ${GITHUB_SHA}
+      ########################################
+      # Upload container images
+      ########################################
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push images to GitHub Container Registry
+        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
+        run: bazel query --noshow_progress 'kind("oci_push", ...)' | xargs -I_target bazel run _target -- --tag ${GITHUB_SHA}
 
-      # ########################################
-      # # Update k8s deployments
-      # ########################################
-      # - name: Update k8s deployments
-      #   if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
-      #   uses: ./.github/workflows/update-k8s-deployments
-      #   with:
-      #     gitlab_api_token: ${{ secrets.GITLAB_API_TOKEN }}
+      ########################################
+      # Update k8s deployments
+      ########################################
+      - name: Update k8s deployments
+        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
+        uses: ./.github/workflows/update-k8s-deployments
+        with:
+          gitlab_api_token: ${{ secrets.GITLAB_API_TOKEN }}
 
-      # ########################################
-      # # Clean up runner
-      # ########################################
-      # - uses: ./.github/workflows/manage-runner-post
-      #   name: Tear down runner
+      ########################################
+      # Clean up runner
+      ########################################
+      - uses: ./.github/workflows/manage-runner-post
+        name: Tear down runner
