ci: fixing ci reusable workflows (#118)
* adding debug prints

* fixing name of the folder

* adding input to workflow_call

* fixing ci

* fixing

* turning into composite action

* reenabling

* fix: Use the correct github action

* Update the bazel cache recreate steps

* adding workflow dispatch and changing cron

* Support building and pushing containers also on pull requests

* pull cache always and push only on main

* adding pushing of cache on updating deps

* making pushing new commits to a branch cancel previous runs of the CI for that branch

* test cancel

* test cancel 2

* Split out the manage-worker-post

* Set shell for post optimize

---------

Co-authored-by: Saša Tomić <sasa.tomic@dfinity.org>

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -5,13 +5,18 @@ on:
       - "main"
   pull_request:
   merge_group:
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
+
 jobs:
   bazel:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v4
-      - uses: ./.github/workflows/setup-bazel
-        name: Setup bazel
+      - name: Setup runner
+        uses: ./.github/workflows/manage-runner-pre
 
       ########################################
       # Build and test
@@ -53,18 +58,18 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Push images to GitHub Container Registry
-        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
+        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
         run: bazel query --noshow_progress 'kind("oci_push", ...)' | xargs -I_target bazel run _target -- --tag ${GITHUB_SHA}
 
       ########################################
       # Update k8s deployments
       ########################################
       - name: Update k8s deployments
-        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
-        uses: ./.github/workflows/update-k8s-deployments.yml
+        if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.head_ref, 'container') || startsWith(github.ref, 'refs/heads/container') || (github.ref == 'refs/heads/main') }}
+        uses: ./.github/workflows/update-k8s-deployments
 
       ########################################
-      # Optimize bazel cache by hard-linking duplicate files
+      # Clean up runner
       ########################################
-      - name: Optimize bazel cache directory before uploading
-        run: bin/optimize-bazel-cache.sh
+      - uses: ./.github/workflows/manage-runner-post
+        name: Tear down runner
