Test streaming output

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -25,22 +25,32 @@ jobs:
       ########################################
       - name: "🚀 Building"
         run: |
-          set +e -x
-          build_output=$(bazel build ... 2>&1)
-          exit_code=$?
-          if [[ $exit_code -ne 0 ]] && grep -q "Digests do not match:" <<< "$build_output"; then
-              export CARGO_BAZEL_REPIN=true
-              build_output=$(bazel build ... 2>&1)
-              git config user.name "GitHub Actions"
-              git config user.email "actions@github.com"
-              git add Cargo.Bazel.lock
-              git commit -m "GITHUB ACTIONS: run bazel REPIN"
-              git push origin HEAD:${{ github.head_ref }}
-              return 1
-              exit 1
-          fi
-          echo "$build_output"
-          exit $exit_code
+          set -x
+          function bazel_build_auto_repin() {
+              local MYTMPDIR="$(mktemp -d)"
+              trap 'rm -rf -- "$MYTMPDIR"' EXIT
+              local logfile="$MYTMPDIR/bazel-out.log" 
+              bazel "$@" 2>&1 | tee "$logfile" >&2
+              local r=${PIPESTATUS[0]}
+              if [ "$r" != "0" ]; then
+                  if grep -q 'Digests do not match' "$logfile" ; then
+                      # Repin necessary; only apply to this build
+                      CARGO_BAZEL_REPIN=true bazel "$@" || return $?
+                      git pull
+                      git config user.name "GitHub Actions"
+                      git config user.email "actions@github.com"
+                      git add Cargo.Bazel.lock
+                      git commit -m "GITHUB ACTIONS: run bazel REPIN"
+                      git push origin HEAD:${{ github.head_ref }}
+                      return 1
+                  else
+                      # Other failure, let's make like a tree and leave
+                      return $r
+                  fi
+              fi
+          }
+          
+          bazel_build_auto_repin build ...
       - run: bazel test ...
         name: "🚀 Testing"
 
